### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Darmody** [jigojigo/frontend#5]

**Comment by calebx** [comment]
https://github.com/jigojigo/frontend/pull/9

**Comment by Darmody** [comment]
@calebx I think this issue haven't been done compelety. You can add a check list.

**Comment by Darmody** [comment]
When you mentioned issue in PR or the reverse way, they will auto connected.

**Comment by Darmody** [comment]
@calebx If #9 is good enough for alpha, we can close this one?
